### ISSUE TITLE
'dotnet run' command fails

### ISSUE THREAD

**Issue by L4ZZA** [deviserplatform/deviserplatform#1]
Followed this steps on Windows 10:
Install .NET Core SDK
Install Node.js (v8.11.4)
Clone this repository git clone https://github.com/deviserplatform/deviserplatform.git into folder "Test"
Run Deviser Platform dotnet run

Since it's not specified, I assumed the command needed to be run from the "Test" folder.
Did so and got this error:
_Couldn't find a project to run. Ensure a project exists in E:\Test, or pass the path to the project using --project._
so I **cd** into deviserplatform and run the command again and got the same error.
**cd ..** back to Test folder and trying to follow the error message. So I run _dotnet run deviserplatform_ and nothing has changed.

What is that command supposed to do? Is it even a requirement (running the solution just works)?

**Comment by karthicksundararajan** [comment]
@L4ZZA 

Welcome to Deviser Platform! Thanks for trying this project. This is probabily a mistake in **Build from source** section. 

Could you change your working directory to `.\deviserplatform\src\Deviser.WI\`?

`cd .\deviserplatform\src\Deviser.WI\`

and then try

`dotnet run`

**Comment by L4ZZA** [comment]
yes it does work that way. Please update the instruction cause that could put people off, especially if they don't have much experience with coding.

**Comment by karthicksundararajan** [comment]
Cool! I have updated the documentation. 

Since the issue has been resolved, closing it.
